cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")
set(package "${work}/explicit module project")
jp_copy_project(multi "${package}")

function(assert_plan mode profile)
    set(cwd "${work}/${mode} ${profile}")
    file(MAKE_DIRECTORY "${cwd}")
    set(options)
    if(profile STREQUAL "release")
        list(APPEND options --release)
        set(flags "<-O2>\n<-g0>\n")
    else()
        set(flags "<-O0>\n<-gfull>\n")
    endif()
    jp_call(1 "${cwd}" "${mode}" --compiler "${COMPILER_SPY}"
        --manifest-path "${package}/joyeer.toml" --verbose ${options})
    if(NOT EXISTS "${cwd}/compiler-record.txt")
        jp_fail("Planner did not invoke the controlled compiler")
    endif()
    file(READ "${cwd}/compiler-record.txt" record)
    string(REPLACE "\\" "/" record "${record}")
    set(expected "<--module-name>\n<sample.app>\n<--module-source>\n<sample.core=${package}/core.joyeer>\n${flags}")
    if(mode STREQUAL "build")
        file(GLOB generations LIST_DIRECTORIES true "${package}/target/${profile}/multi/build-*")
        list(LENGTH generations count)
        if(NOT count EQUAL 1)
            jp_fail("Expected one newly claimed ${profile} generation, found ${count}")
        endif()
        list(GET generations 0 generation)
        string(APPEND expected "<-o>\n<${generation}/multi${EXECUTABLE_SUFFIX}>\n")
    else()
        jp_no_outputs("${package}")
    endif()
    string(APPEND expected "<-->\n<${package}/implementation files/helper.joyeer>\n<${package}/main.joyeer>\n")
    if(NOT record STREQUAL expected)
        jp_fail("Exact compiler argv mismatch:\nexpected:\n${expected}\nactual:\n${record}")
    endif()
    jp_contains("${jp_err}" "37")
    jp_contains("${jp_err}" "--module-name")
    jp_contains("${jp_err}" "sample.core=")
    if(profile STREQUAL "release")
        jp_contains("${jp_err}" "-O2")
        jp_contains("${jp_err}" "-g0")
    else()
        jp_contains("${jp_err}" "-O0")
        jp_contains("${jp_err}" "-gfull")
    endif()
    set(last_record "${record}" PARENT_SCOPE)
endfunction()

assert_plan(check debug)
set(original_record "${last_record}")

# Equivalent source/module declaration order must not change the argument plan.
set(reordered "schema-version = 1\n[package]\nname = 'multi'\nversion = '1.2.3'\n")
string(APPEND reordered "[[modules]]\nname = 'sample.core'\nsources = ['core.joyeer']\ndependencies = []\n")
string(APPEND reordered "[[modules]]\nname = 'sample.app'\nsources = ['implementation files/helper.joyeer', 'main.joyeer']\ndependencies = ['sample.core']\n")
string(APPEND reordered "[[targets]]\nname = 'multi'\nkind = 'bin'\nmodule = 'sample.app'\n")
jp_write_bytes("${package}/joyeer.toml" "${reordered}")
set(reorder_cwd "${work}/reordered caller")
file(MAKE_DIRECTORY "${reorder_cwd}")
jp_call(1 "${reorder_cwd}" check --compiler "${COMPILER_SPY}"
    --manifest-path "${package}/joyeer.toml")
file(READ "${reorder_cwd}/compiler-record.txt" reordered_record)
string(REPLACE "\\" "/" reordered_record "${reordered_record}")
if(NOT reordered_record STREQUAL original_record)
    jp_fail("Equivalent declarations produced different compiler argv")
endif()
jp_no_outputs("${package}")
assert_plan(check release)
assert_plan(build debug)
assert_plan(build release)
jp_artifacts("${package}" debug multi 0)
jp_artifacts("${package}" release multi 0)

# A diamond includes its shared leaf exactly once, excludes an unrelated
# module, and sorts module/source identities independently of declaration order.
set(diamond "${work}/diamond project")
file(MAKE_DIRECTORY "${diamond}")
set(manifest "schema-version = 1\n[package]\nname = 'diamond'\nversion = '0.1.0'\n")
string(APPEND manifest "[[modules]]\nname = 'graph.root'\nsources = ['z-root.joyeer', 'a-root.joyeer']\ndependencies = ['graph.right', 'graph.left']\n")
string(APPEND manifest "[[modules]]\nname = 'graph.unselected'\nsources = ['unselected.joyeer']\ndependencies = []\n")
string(APPEND manifest "[[modules]]\nname = 'graph.right'\nsources = ['right.joyeer']\ndependencies = ['graph.leaf']\n")
string(APPEND manifest "[[modules]]\nname = 'graph.leaf'\nsources = ['z-leaf.joyeer', 'a-leaf.joyeer']\ndependencies = []\n")
string(APPEND manifest "[[modules]]\nname = 'graph.left'\nsources = ['left.joyeer']\ndependencies = ['graph.leaf']\n")
string(APPEND manifest "[[targets]]\nname = 'diamond'\nkind = 'bin'\nmodule = 'graph.root'\n")
jp_write_bytes("${diamond}/joyeer.toml" "${manifest}")
set(cwd "${work}/diamond caller")
file(MAKE_DIRECTORY "${cwd}")
jp_call(1 "${cwd}" check --compiler "${COMPILER_SPY}"
    --manifest-path "${diamond}/joyeer.toml")
jp_no_runtime_error()
if(NOT EXISTS "${cwd}/compiler-record.txt")
    jp_fail("Diamond closure did not reach the controlled compiler")
endif()
file(READ "${cwd}/compiler-record.txt" record)
string(REPLACE "\\" "/" record "${record}")
set(expected "<--module-name>\n<graph.root>\n")
foreach(pair IN ITEMS "graph.leaf=a-leaf.joyeer" "graph.leaf=z-leaf.joyeer"
        "graph.left=left.joyeer" "graph.right=right.joyeer")
    string(REPLACE "=" ";" fields "${pair}")
    list(GET fields 0 module_name)
    list(GET fields 1 source_name)
    string(APPEND expected "<--module-source>\n<${module_name}=${diamond}/${source_name}>\n")
endforeach()
string(APPEND expected "<-O0>\n<-gfull>\n<-->\n<${diamond}/a-root.joyeer>\n<${diamond}/z-root.joyeer>\n")
if(NOT record STREQUAL expected)
    jp_fail("Diamond exact argv mismatch:\nexpected:\n${expected}\nactual:\n${record}")
endif()
jp_contains("${jp_err}" "exited with status 37")
jp_no_outputs("${diamond}")

# Even --target cannot hide a cycle wholly outside the selected closure.
string(REPLACE "name = 'graph.unselected'\nsources = ['unselected.joyeer']\ndependencies = []"
    "name = 'graph.unselected'\nsources = ['unselected.joyeer']\ndependencies = ['graph.unselected']"
    cyclic "${manifest}")
jp_write_bytes("${diamond}/joyeer.toml" "${cyclic}")
set(cwd "${work}/unselected cycle caller")
file(MAKE_DIRECTORY "${cwd}")
jp_call(1 "${cwd}" build --target diamond --compiler "${COMPILER_SPY}"
    --manifest-path "${diamond}/joyeer.toml")
string(FIND "${cyclic}" "name = 'graph.unselected'" name_pos)
string(SUBSTRING "${cyclic}" 0 "${name_pos}" before_name)
string(FIND "${before_name}" "[[modules]]" cycle_pos REVERSE)
jp_manifest_diagnostic("${diamond}/joyeer.toml" "${cyclic}" "${cycle_pos}")
jp_contains("${jp_err}" "module dependency cycle: graph.unselected -> graph.unselected")
if(EXISTS "${cwd}/compiler-record.txt")
    jp_fail("An unselected cycle reached the compiler")
endif()
jp_no_outputs("${diamond}")
message(STATUS "joypm exact named-module/source/profile argv acceptance passed")