cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")

# There is no manifest here; neither operation needs a compiler argument.
jp_call(0 "${outside}" --help)
jp_contains("${jp_out}" "joypm")
foreach(command IN ITEMS init check build run test)
    jp_contains("${jp_out}" "${command}")
endforeach()
if(NOT jp_err STREQUAL "")
    jp_fail("Help must not write stderr")
endif()
jp_call(0 "${outside}" --version)
if(NOT jp_out MATCHES "joypm[^\n]*[0-9]+\\.[0-9]+\\.[0-9]+" OR
   NOT jp_err STREQUAL "")
    jp_fail("Version must identify joypm and a numeric version on stdout only")
endif()

jp_usage()
jp_usage(unknown-command)
jp_usage(--unknown)
jp_usage(--help --help)
jp_usage(--version --version)
jp_usage(--help --version)
jp_usage(build)
jp_usage(build --compiler)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --unknown)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --compiler missing)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --manifest-path)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --manifest-path a --manifest-path b)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --release --release)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --verbose --verbose)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --target a --target b)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" --target)
jp_usage(build --compiler "${JOYEER_EXECUTABLE}" -- forwarded)
jp_usage(check --compiler "${JOYEER_EXECUTABLE}" --target a)
jp_usage(init)
jp_usage(init directory)
jp_usage(init directory --name)
jp_usage(init directory --name one --name two)
jp_usage(init directory --name sample --compiler "${JOYEER_EXECUTABLE}")
jp_usage(run --compiler "${JOYEER_EXECUTABLE}" unexpected-positional)
jp_no_outputs("${outside}")

jp_call(1 "${outside}" check --compiler "${JOYEER_EXECUTABLE}")
if(jp_err STREQUAL "")
    jp_fail("Missing default manifest must be a tool error on stderr")
endif()

# Default manifest lookup must not walk to a parent directory.
set(parent "${work}/parent")
jp_copy_project(single "${parent}")
file(MAKE_DIRECTORY "${parent}/nested")
jp_call(1 "${parent}/nested" check --compiler "${JOYEER_EXECUTABLE}")
jp_no_outputs("${parent}")
message(STATUS "joypm CLI/status/stream/no-upward-search acceptance passed")