cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")

function(install_component prefix component)
    execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIRECTORY}"
        --config "${TEST_CONFIGURATION}" --component "${component}" --prefix "${prefix}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Product installation failed (${result}):\n${output}\n${error}")
    endif()
endfunction()

function(assert_inventory prefix)
    file(GLOB actual RELATIVE "${prefix}" "${prefix}/*")
    set(expected ${ARGN})
    list(SORT actual)
    list(SORT expected)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Incorrect product inventory at ${prefix}:\nexpected ${expected}\nactual ${actual}")
    endif()
endfunction()

set(runtime_only "${work}/runtime component")
install_component("${runtime_only}" JoyeerRuntime)
assert_inventory("${runtime_only}" ${RUNTIME_FILE_NAMES} licenses)
set(product_only "${work}/tool component")
install_component("${product_only}" PRODUCT)
set(tool_files "joypm${EXECUTABLE_SUFFIX}")
if(WIN32 AND TEST_CONFIGURATION STREQUAL "Debug")
    list(APPEND tool_files joypm.pdb)
endif()
assert_inventory("${product_only}" ${tool_files})

set(stage "${work}/combined package")
install_component("${stage}" JoyeerRuntime)
install_component("${stage}" PRODUCT)
assert_inventory("${stage}" ${RUNTIME_FILE_NAMES} ${tool_files} licenses)
file(SHA256 "${LICENSE_SOURCE}" original)
file(SHA256 "${stage}/licenses/LICENSE" installed)
if(NOT installed STREQUAL original)
    message(FATAL_ERROR "Installed Joyeer license changed")
endif()
assert_inventory("${stage}/licenses" LICENSE)
foreach(name IN LISTS RUNTIME_FILE_NAMES tool_files)
    file(SIZE "${stage}/${name}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Empty installed product artifact: ${name}")
    endif()
endforeach()

# U+96EA and U+1F980, encoded as UTF-8 for a relocated supplementary-plane path.
string(ASCII 233 155 170 240 159 166 128 unicode)
set(relocated "${work}/relocated package ${unicode}")
file(RENAME "${stage}" "${relocated}")
set(JOYPM_EXECUTABLE "${relocated}/joypm${EXECUTABLE_SUFFIX}")
set(JOYEER_EXECUTABLE "${relocated}/${COMPILER_FILE_NAME}")
jp_call(0 "${outside}" --version)
if(NOT jp_out STREQUAL "joypm 0.1.0\n" OR NOT jp_err STREQUAL "")
    jp_fail("Relocated installed joypm changed its version/stream contract")
endif()
set(package "${work}/installed workflow")
jp_call(0 "${outside}" init "${package}" --name installed)
file(READ "${package}/joyeer.toml" manifest)
string(APPEND manifest "\n[[targets]]\nname = 'installed-tests'\nkind = 'test'\nmodule = 'app.main'\n")
jp_write_bytes("${package}/joyeer.toml" "${manifest}")
jp_call(0 "${outside}" check --compiler "${JOYEER_EXECUTABLE}"
    --manifest-path "${package}/joyeer.toml")
jp_no_outputs("${package}")
foreach(profile IN ITEMS debug release)
    set(options)
    if(profile STREQUAL "release")
        list(APPEND options --release)
    endif()
    jp_call(0 "${outside}" build --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${package}/joyeer.toml" ${options})
    jp_artifacts("${package}" "${profile}" installed 1)
    jp_call(0 "${outside}" run --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${package}/joyeer.toml" ${options})
    if(NOT jp_out STREQUAL "Hello, Joyeer!\n")
        jp_fail("Installed compiler/backend/runtime/tool workflow did not execute")
    endif()
    jp_call(0 "${outside}" test --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${package}/joyeer.toml" ${options})
    jp_contains("${jp_out}" "1 test: 1 passed, 0 build-fail, 0 run-fail")
    jp_artifacts("${package}" "${profile}" installed-tests 1)
    jp_no_runtime_error()
endforeach()
message(STATUS "joypm local install components, exact inventory/license and relocated workflows passed")
