cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")
set(artifact "${JOYPM_EXECUTABLE}")
if(TEST_CONFIGURATION STREQUAL "Debug")
    get_filename_component(directory "${JOYPM_EXECUTABLE}" DIRECTORY)
    set(artifact "${directory}/joypm.pdb")
endif()
if(NOT EXISTS "${artifact}" OR IS_DIRECTORY "${artifact}")
    message(FATAL_ERROR "Missing bootstrap output before regeneration: ${artifact}")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef backup_id)
set(backup "${artifact}.bootstrap-${backup_id}")
file(RENAME "${artifact}" "${backup}")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD_DIRECTORY}"
    --config "${TEST_CONFIGURATION}" --target joypm
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
if(NOT result STREQUAL "0" OR NOT EXISTS "${artifact}" OR IS_DIRECTORY "${artifact}")
    file(RENAME "${backup}" "${artifact}")
    message(FATAL_ERROR "Missing bootstrap output did not regenerate (${result}):\n${output}\n${error}")
endif()
file(SIZE "${artifact}" size)
if(size EQUAL 0)
    file(RENAME "${backup}" "${artifact}")
    message(FATAL_ERROR "Bootstrap regenerated an empty output: ${artifact}")
endif()
jp_call(0 "${outside}" --version)
if(NOT jp_out STREQUAL "joypm 0.1.0\n" OR NOT jp_err STREQUAL "")
    jp_fail("Regenerated bootstrap tool did not execute")
endif()
file(REMOVE "${backup}")
message(STATUS "joypm missing ${TEST_CONFIGURATION} bootstrap output regenerated and executed")
