cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")
set(jp_timeout 8)
file(READ "${FIXTURE_DIR}/single/joyeer.toml" base)

function(reject_manifest name contents)
    jp_reject_manifest("${name}" "${contents}" ${ARGN})
endfunction()

function(reject_replacement name old replacement)
    string(FIND "${base}" "${old}" at)
    if(at LESS 0)
        message(FATAL_ERROR "Manifest test mutation is missing '${old}'")
    endif()
    string(REPLACE "${old}" "${replacement}" changed "${base}")
    reject_manifest("${name}" "${changed}")
endfunction()

reject_manifest(empty "" 0)
reject_replacement(schema-version "schema-version = 1" "schema-version = 2")
reject_replacement(schema-type "schema-version = 1" "schema-version = '1'")
reject_replacement(schema-missing "schema-version = 1" "")
reject_replacement(schema-duplicate "schema-version = 1" "schema-version = 1\nschema-version = 1")
reject_replacement(package-duplicate-key "version = \"0.1.0\"" "version = \"0.1.0\"\nversion = \"0.1.0\"")
reject_replacement(package-duplicate-table "[[modules]]" "[package]\n[[modules]]")
reject_replacement(package-missing-version "version = \"0.1.0\"" "")
reject_replacement(package-wrong-type "version = \"0.1.0\"" "version = 1")
reject_replacement(package-invalid-version "version = \"0.1.0\"" "version = '01.1.0'")
reject_replacement(package-invalid-name "name = \"sample\"" "name = 'bad name'")
reject_replacement(root-unknown "schema-version = 1" "schema-version = 1\nunknown = 'field'")
reject_replacement(package-unknown "[package]" "[package]\nunknown = 'field'")
reject_replacement(module-unknown "[[modules]]" "[[modules]]\nunknown = []")
reject_replacement(target-unknown "[[targets]]" "[[targets]]\nunknown = 'field'")
reject_replacement(unknown-table "[package]" "[unexpected]")
reject_replacement(module-empty-sources "sources = [\"main.joyeer\"]" "sources = []")
reject_replacement(module-source-type "sources = [\"main.joyeer\"]" "sources = 'main.joyeer'")
reject_replacement(module-source-element-type "sources = [\"main.joyeer\"]" "sources = [1]")
reject_replacement(module-source-duplicate "sources = [\"main.joyeer\"]" "sources = ['main.joyeer', 'main.joyeer']")
reject_replacement(module-key-duplicate "dependencies = []" "dependencies = []\ndependencies = []")
reject_replacement(module-name-invalid "name = \"sample.app\"" "name = 'sample..app'")
reject_replacement(module-unknown-dependency "dependencies = []" "dependencies = ['missing.module']")
reject_replacement(module-cycle "dependencies = []" "dependencies = ['sample.app']")
reject_replacement(module-dependency-type "dependencies = []" "dependencies = 'sample.core'")
reject_replacement(module-parent-source "sources = [\"main.joyeer\"]" "sources = ['../main.joyeer']")
reject_replacement(module-drive-relative "sources = [\"main.joyeer\"]" "sources = ['C:main.joyeer']")
reject_replacement(target-unknown-module "module = \"sample.app\"" "module = 'missing.module'")
reject_replacement(target-kind "kind = \"bin\"" "kind = 'library'")
reject_replacement(target-kind-type "kind = \"bin\"" "kind = []")
reject_replacement(target-module-missing "module = \"sample.app\"" "")
string(FIND "${base}" "[[targets]]" targets_at)
string(SUBSTRING "${base}" 0 "${targets_at}" no_targets)
reject_manifest(no-targets "${no_targets}")
reject_manifest(target-duplicate "${base}\n[[targets]]\nname = 'sample'\nkind = 'test'\nmodule = 'sample.app'\n")
reject_manifest(module-duplicate "${base}\n[[modules]]\nname = 'sample.app'\nsources = ['other.joyeer']\ndependencies = []\n")
if(WIN32)
    reject_replacement(reserved-name "name = \"sample\"" "name = 'CON'")
    reject_manifest(case-folded-target "${base}\n[[targets]]\nname = 'SAMPLE'\nkind = 'bin'\nmodule = 'sample.app'\n")
endif()
reject_replacement(unsupported-inline-table "[package]" "package = { name = 'sample' }")
reject_replacement(unsupported-float "schema-version = 1" "schema-version = 1.0")
reject_replacement(unsupported-date "version = \"0.1.0\"" "version = 2026-10-01")
reject_replacement(unsupported-quoted-key "schema-version = 1" "\"schema-version\" = 1")
reject_replacement(unsupported-dotted-key "schema-version = 1" "schema.version = 1")
reject_replacement(unsupported-multiline "version = \"0.1.0\"" "version = \"\"\"0.1.0\"\"\"")
reject_replacement(truncated-array "sources = [\"main.joyeer\"]" "sources = [\"main.joyeer\"")
reject_replacement(truncated-string "version = \"0.1.0\"" "version = \"0.1.0")
reject_manifest(trailing-garbage "${base}\n@")
reject_replacement(trailing-value "schema-version = 1" "schema-version = 1 false")
reject_replacement(invalid-escape "version = \"0.1.0\"" [=[version = "0.1.0\q"]=])
reject_replacement(surrogate-escape "sources = [\"main.joyeer\"]" [=[sources = ["\uD800.joyeer"]]=])
reject_replacement(out-of-range-escape "sources = [\"main.joyeer\"]" [=[sources = ["\U00110000.joyeer"]]=])
reject_replacement(truncated-unicode-escape "sources = [\"main.joyeer\"]" [=[sources = ["\u12"]]=])
reject_replacement(nonhex-unicode-escape "sources = [\"main.joyeer\"]" [=[sources = ["\uZZZZ"]]=])
string(ASCII 255 invalid_byte)
reject_manifest(invalid-utf8 "${base}\n# ${invalid_byte}\n" 0)
string(ASCII 192 175 overlong)
reject_replacement(overlong-utf8 "main.joyeer" "${overlong}.joyeer")
string(ASCII 237 160 128 surrogate)
reject_manifest(utf8-surrogate "${base}\n# ${surrogate}\n")
string(REPEAT "[" 64 nested)
reject_replacement(bounded-nesting "sources = [\"main.joyeer\"]" "sources = ${nested}")
string(REPEAT "x" 1048577 long_input)
reject_manifest(bounded-long-malformed "${long_input}" 65536)

# Locations are in the original source bytes, not decoded characters or a
# newline-normalized copy. Place errors after UTF-8 and both escape widths.
set(location_input "# 雪🦀\r\nschema-version = 1\r\nunknown = 'field'\r\n")
string(FIND "${location_input}" "unknown" error_pos)
reject_manifest(location-crlf-utf8 "${location_input}" "${error_pos}")
set(location_input [=[schema-version = 1
[package]
name = 'sample'
version = "\u0030.\U00000031.0" @
]=])
string(FIND "${location_input}" "@" error_pos)
reject_manifest(location-after-escapes "${location_input}" "${error_pos}")
string(REPLACE "sources = [\"main.joyeer\"]" "sources = [\"雪🦀.joyeer\"] @" location_input "${base}")
set(location_input "# 雪🦀\r\n${location_input}")
string(FIND "${location_input}" "@" error_pos)
reject_manifest(location-after-utf8 "${location_input}" "${error_pos}")
string(REPLACE "sources = [\"main.joyeer\"]" "sources = [\"main.joyeer\"" location_input "${base}")
string(FIND "${location_input}" "dependencies" error_pos)
reject_manifest(location-truncated-array "${location_input}" "${error_pos}")

# A two-node cycle with otherwise valid records must also be rejected.
string(REPLACE "dependencies = []" "dependencies = ['sample.core']" cycle "${base}")
string(APPEND cycle "\n[[modules]]\nname = 'sample.core'\nsources = ['core.joyeer']\ndependencies = ['sample.app']\n")
reject_manifest(two-node-cycle "${cycle}")
string(REPLACE "dependencies = []" "dependencies = ['sample.core', 'sample.core']" repeated "${base}")
string(APPEND repeated "\n[[modules]]\nname = 'sample.core'\nsources = ['core.joyeer']\ndependencies = []\n")
reject_manifest(repeated-dependency "${repeated}")

# Accepted spellings must actually reach the controlled compiler, whose 37
# maps to joypm's 1. Fresh caller directories avoid exclusive-record failures.
function(accept_manifest name contents)
    set(package "${work}/${name}")
    set(cwd "${work}/caller ${name}")
    file(MAKE_DIRECTORY "${package}" "${cwd}")
    file(WRITE "${package}/joyeer.toml" "${contents}")
    jp_call(1 "${cwd}" check --compiler "${COMPILER_SPY}"
        --manifest-path "${package}/joyeer.toml")
    jp_no_runtime_error()
    if(NOT jp_out STREQUAL "" OR NOT EXISTS "${cwd}/compiler-record.txt")
        jp_fail("Accepted manifest ${name} did not reach the controlled compiler")
    endif()
    file(READ "${cwd}/compiler-record.txt" record)
    string(REPLACE "\\" "/" record "${record}")
    set(expected "<--module-name>\n<sample.app>\n<-O0>\n<-gfull>\n<-->\n<${package}/main.joyeer>\n")
    if(NOT record STREQUAL expected)
        jp_fail("Accepted manifest ${name} produced different decoded compiler argv:\n${record}")
    endif()
    jp_contains("${jp_err}" "exited with status 37")
    jp_no_outputs("${package}")
endfunction()

foreach(schema IN ITEMS +1 0x1 0o1 0b1 0x0_1)
    string(REPLACE "schema-version = 1" "schema-version = ${schema}" accepted "${base}")
    accept_manifest("accepted-schema-${schema}" "${accepted}")
endforeach()
string(REPLACE "sources = [\"main.joyeer\"]"
    [=[sources = ["\u006dain.joyeer",]]=] accepted "${base}")
string(REPLACE "version = \"0.1.0\"" "version = '0.1.0' # metadata" accepted "${accepted}")
string(REPLACE "\n" "\r\n" accepted "${accepted}")
accept_manifest(accepted-crlf-short-escape "# profile acceptance\r\n${accepted}")
string(REPLACE "sources = [\"main.joyeer\"]"
    [=[sources = ["\U0000006Dain.joyeer"]]=] accepted "${base}")
string(REGEX REPLACE "\n$" "" accepted "${accepted}")
accept_manifest(accepted-wide-escape-eof "${accepted}")

# Accepted profile forms go through the real compiler: comments, CRLF, literal
# strings, string-array trailing commas and both Unicode escape widths.
set(package "${work}/valid escaped manifest")
jp_copy_project(single "${package}")
string(REPLACE "sources = [\"main.joyeer\"]"
    [=[sources = ["\u006dain.joyeer",]]=] valid "${base}")
string(REPLACE "version = \"0.1.0\"" "version = '0.1.0' # metadata" valid "${valid}")
string(REPLACE "\n" "\r\n" valid "${valid}")
file(WRITE "${package}/joyeer.toml" "# profile acceptance\r\n${valid}")
set(jp_timeout 60)
jp_call(0 "${outside}" check --compiler "${JOYEER_EXECUTABLE}"
    --manifest-path "${package}/joyeer.toml")
string(REPLACE "sources = [\"main.joyeer\"]"
    [=[sources = ["\U0000006Dain.joyeer"]]=] valid "${base}")
string(REGEX REPLACE "\n$" "" valid "${valid}")
file(WRITE "${package}/joyeer.toml" "${valid}")
jp_call(0 "${outside}" check --compiler "${JOYEER_EXECUTABLE}"
    --manifest-path "${package}/joyeer.toml")
jp_no_outputs("${package}")
message(STATUS "joypm strict manifest/profile/malformed-input acceptance passed")