cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")
if(NOT EXISTS "${SELF_BUILD_PROJECT}/joyeer.toml")
    message(FATAL_ERROR "Configure the joypm self-build project before running acceptance")
endif()
set(package "${work}/self build project")
file(MAKE_DIRECTORY "${package}")
file(COPY "${SELF_BUILD_PROJECT}/" DESTINATION "${package}" PATTERN "target" EXCLUDE)
jp_call(0 "${outside}" check --compiler "${JOYEER_EXECUTABLE}"
    --manifest-path "${package}/joyeer.toml")
jp_no_outputs("${package}")
set(bootstrap "${JOYPM_EXECUTABLE}")

foreach(profile IN ITEMS debug release)
    set(options)
    if(profile STREQUAL "release")
        list(APPEND options --release)
    endif()
    set(JOYPM_EXECUTABLE "${bootstrap}")
    jp_call(0 "${outside}" build --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${package}/joyeer.toml" ${options})
    jp_artifacts("${package}" "${profile}" joypm 1)
    list(GET jp_artifact_list 0 self_built)
    if(WIN32 AND profile STREQUAL "debug")
        get_filename_component(directory "${self_built}" DIRECTORY)
        if(NOT EXISTS "${directory}/joypm.pdb")
            jp_fail("Debug self-build did not produce its PDB")
        endif()
    endif()
    set(JOYPM_EXECUTABLE "${self_built}")
    jp_call(0 "${outside}" --version)
    if(NOT jp_out STREQUAL "joypm 0.1.0\n" OR NOT jp_err STREQUAL "")
        jp_fail("Self-built joypm changed its version/stream contract")
    endif()
    jp_call(0 "${outside}" --help)
    jp_contains("${jp_out}" "local Joyeer project manager")
    set(smoke "${work}/self built ${profile} project")
    jp_call(0 "${outside}" init "${smoke}" --name self-built)
    file(READ "${smoke}/joyeer.toml" manifest)
    string(APPEND manifest "\n[[targets]]\nname = 'self-tests'\nkind = 'test'\nmodule = 'app.main'\n")
    jp_write_bytes("${smoke}/joyeer.toml" "${manifest}")
    jp_call(0 "${outside}" check --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${smoke}/joyeer.toml" ${options})
    jp_no_outputs("${smoke}")
    jp_call(0 "${outside}" build --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${smoke}/joyeer.toml" ${options})
    jp_artifacts("${smoke}" "${profile}" self-built 1)
    jp_call(0 "${outside}" run --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${smoke}/joyeer.toml" ${options})
    if(NOT jp_out STREQUAL "Hello, Joyeer!\n")
        jp_fail("Self-built joypm could not execute a freshly scaffolded project")
    endif()
    jp_call(0 "${outside}" test --compiler "${JOYEER_EXECUTABLE}"
        --manifest-path "${smoke}/joyeer.toml" ${options})
    jp_contains("${jp_out}" "1 test: 1 passed, 0 build-fail, 0 run-fail")
    jp_artifacts("${smoke}" "${profile}" self-tests 1)
    jp_no_runtime_error()
endforeach()

# The Release-built tool must itself plan and execute another self-build.
jp_call(0 "${outside}" build --compiler "${JOYEER_EXECUTABLE}"
    --manifest-path "${package}/joyeer.toml" --release --target joypm)
jp_artifacts("${package}" release joypm 2)
set(JOYPM_EXECUTABLE "${package}/target/release/joypm/build-2/joypm${EXECUTABLE_SUFFIX}")
jp_call(0 "${outside}" --version)
if(NOT jp_out STREQUAL "joypm 0.1.0\n" OR NOT jp_err STREQUAL "")
    jp_fail("Second-stage self-built tool did not execute")
endif()
message(STATUS "joypm Debug/Release self-build, second-stage build and declared-test workflows passed")
