cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers.cmake")

set(package "${work}/new project")
jp_call(0 "${outside}" init "${package}" --name new-project)
file(GLOB_RECURSE initialized_sources LIST_DIRECTORIES false
    RELATIVE "${package}" "${package}/*.joyeer")
list(LENGTH initialized_sources source_count)
if(NOT source_count EQUAL 1)
    jp_fail("init must create exactly one minimal Joyeer source")
endif()
set(initialized_files joyeer.toml .gitignore ${initialized_sources})
foreach(path IN LISTS initialized_files)
    if(NOT EXISTS "${package}/${path}" OR IS_DIRECTORY "${package}/${path}")
        jp_fail("init did not create ${path}")
    endif()
    file(SHA256 "${package}/${path}" "before_${path}")
endforeach()
file(READ "${package}/.gitignore" ignore)
jp_contains("${ignore}" "target")
jp_call(0 "${outside}" check --compiler "${JOYEER_EXECUTABLE}"
    --manifest-path "${package}/joyeer.toml")
jp_no_outputs("${package}")
jp_call(1 "${outside}" init "${package}" --name replacement)
foreach(path IN LISTS initialized_files)
    file(SHA256 "${package}/${path}" after)
    if(NOT after STREQUAL "${before_${path}}")
        jp_fail("Rejected init changed ${path}")
    endif()
endforeach()

set(empty "${work}/existing empty")
file(MAKE_DIRECTORY "${empty}")
jp_call(0 "${outside}" init "${empty}" --name empty)
set(nonempty "${work}/nonempty")
file(MAKE_DIRECTORY "${nonempty}")
file(WRITE "${nonempty}/sentinel" "preserve me")
jp_call(1 "${outside}" init "${nonempty}" --name sample)
file(READ "${nonempty}/sentinel" sentinel)
if(NOT sentinel STREQUAL "preserve me" OR EXISTS "${nonempty}/joyeer.toml")
    jp_fail("Rejected nonempty initialization changed files")
endif()
foreach(path IN ITEMS joyeer.toml main.joyeer .gitignore)
    set(collision "${work}/collision ${path}")
    file(MAKE_DIRECTORY "${collision}")
    file(WRITE "${collision}/${path}" "do not overwrite")
    jp_call(1 "${outside}" init "${collision}" --name sample)
    file(READ "${collision}/${path}" sentinel)
    if(NOT sentinel STREQUAL "do not overwrite")
        jp_fail("init overwrote collision ${path}")
    endif()
    file(GLOB children RELATIVE "${collision}" "${collision}/*" "${collision}/.*")
    list(LENGTH children count)
    if(NOT count EQUAL 1)
        jp_fail("init partially populated a destination known to be nonempty")
    endif()
endforeach()
set(blocked "${work}/blocked")
file(WRITE "${blocked}" "ordinary file")
jp_call(1 "${outside}" init "${blocked}" --name sample)
jp_call(1 "${outside}" init "${work}/missing parent/project" --name sample)
if(EXISTS "${work}/missing parent")
    jp_fail("init must require an existing parent")
endif()
foreach(name IN ITEMS "bad name" "../escape" "雪" "bad/name")
    jp_call(2 "${outside}" init "${work}/invalid name" --name "${name}")
    if(EXISTS "${work}/invalid name")
        jp_fail("An invalid project name created a destination")
    endif()
endforeach()
if(WIN32)
    jp_call(2 "${outside}" init "${work}/invalid name" --name CON)
    if(EXISTS "${work}/invalid name")
        jp_fail("A reserved Windows project name created a destination")
    endif()
endif()
message(STATUS "joypm initialization/collision acceptance passed")